# src/report.py
# Generates a Markdown debug report summarising the full pipeline result.

from datetime import datetime
from pathlib import Path


def generate_report(
    parsed: dict,
    retrieved: dict,
    diagnosis: dict,
    fixed_code: str = "",
    patched_file: str = "",
) -> str:
    """Build a Markdown report from all pipeline stages.

    Returns the report as a string.
    """
    now = datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    conf = diagnosis.get("confidence", "MEDIUM")
    conf_emoji = {"HIGH": "🟢", "MEDIUM": "🟡", "LOW": "🔴"}.get(conf, "🟡")

    lines = [
        "# 🐛 AI Debug Report",
        f"_Generated: {now}_",
        "",
        "---",
        "",
        "## 📋 Error Summary",
        "",
        f"| Field | Value |",
        f"|---|---|",
        f"| **Error Type** | `{parsed['error_type']}` |",
        f"| **Message** | `{parsed['message']}` |",
        f"| **File** | `{parsed['file']}` |",
        f"| **Line** | `{parsed['line']}` |",
        f"| **Function** | `{parsed['function']}` |",
        f"| **Confidence** | {conf_emoji} {conf} |",
        "",
        "---",
        "",
    ]

    # ── Root cause ──────────────────────────────────────────────────────────────
    lines += [
        "## 🔍 Root Cause",
        "",
        diagnosis.get("root_cause", "_Not available._"),
        "",
        "---",
        "",
    ]

    # ── Relevant source ─────────────────────────────────────────────────────────
    if retrieved.get("context_src"):
        lines += [
            "## 📄 Crash Context",
            "",
            "```",
            retrieved["context_src"],
            "```",
            "",
            "---",
            "",
        ]

    # ── Explanation ─────────────────────────────────────────────────────────────
    lines += [
        "## 💡 Explanation",
        "",
        diagnosis.get("explanation", "_Not available._"),
        "",
        "---",
        "",
    ]

    # ── Fix ─────────────────────────────────────────────────────────────────────
    fix_section = diagnosis.get("fix", "")
    if fix_section:
        lines += [
            "## ✅ Suggested Fix",
            "",
            fix_section,
            "",
        ]

    if fixed_code:
        lines += [
            "### Extracted Code",
            "",
            "```python",
            fixed_code,
            "```",
            "",
        ]

    if patched_file:
        lines += [
            f"> Patched file written to: `{patched_file}`",
            "",
        ]

    lines += ["---", "", "_Report generated by AI Software Debugging Assistant_"]
    return "\n".join(lines)


def save_report(report_text: str, output_path: str) -> str:
    """Write the report to a file and return the path."""
    p = Path(output_path)
    p.parent.mkdir(parents=True, exist_ok=True)
    p.write_text(report_text, encoding="utf-8")
    return str(p)
